"""Align execution fill order nullability

Revision ID: 21b83a4260cf
Revises: 65f5be103c59
Create Date: 2026-09-20 11:44:33.264667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21b83a4260cf'
down_revision: Union[str, Sequence[str], None] = '65f5be103c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execution_fills', 'execution_order_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execution_fills', 'execution_order_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
