"""add parameters to analysis runs

Revision ID: 373d4379d726
Revises: 3b296d4b2532
Create Date: 2026-09-07 20:19:34.398223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '373d4379d726'
down_revision: Union[str, Sequence[str], None] = '3b296d4b2532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_runs', sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.execute("UPDATE analysis_runs SET parameters = '{}'::jsonb WHERE parameters IS NULL")
    op.alter_column("analysis_runs", "parameters", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_runs', 'parameters')
    # ### end Alembic commands ###
