"""add analysis run

Revision ID: 3b296d4b2532
Revises: ac61f38d3b61
Create Date: 2026-08-31 12:44:34.487199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b296d4b2532'
down_revision: Union[str, Sequence[str], None] = 'ac61f38d3b61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
    sa.Column('analysis_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_analysis_type'), 'analysis_runs', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_analysis_runs_created_by'), 'analysis_runs', ['created_by'], unique=False)
    op.create_index(op.f('ix_analysis_runs_dataset_id'), 'analysis_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_dataset_version_id'), 'analysis_runs', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_organization_id'), 'analysis_runs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_project_id'), 'analysis_runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_status'), 'analysis_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_runs_status'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_project_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_organization_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_dataset_version_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_dataset_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_created_by'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_analysis_type'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    # ### end Alembic commands ###
