"""create execution review issues

Revision ID: 62972371275e
Revises: c9a5a3a89c58
Create Date: 2026-09-18 21:24:25.549856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62972371275e'
down_revision: Union[str, Sequence[str], None] = 'c9a5a3a89c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_review_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
    sa.Column('issue_code', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('observed_value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('threshold', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("severity IN ('MEDIUM', 'HIGH', 'CRITICAL')", name='ck_execution_review_issue_order_version_code'),
    sa.CheckConstraint("status IN ('OPEN', 'ACKNOWLEDGED', 'IN_REVIEW', 'RESOLVED', 'IGNORED')", name='ck_execution_review_issue_status'),
    sa.CheckConstraint('threshold IS NULL OR threshold >= 0', name='ck_execution_review_issue_threshold_non_negative'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['execution_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'order_id', 'dataset_version_id', 'issue_code', name='uq_execution_review_issue_order_version_code')
    )
    op.create_index(op.f('ix_execution_review_issues_assigned_to'), 'execution_review_issues', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_execution_review_issues_dataset_id'), 'execution_review_issues', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_execution_review_issues_dataset_version_id'), 'execution_review_issues', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_execution_review_issues_issue_code'), 'execution_review_issues', ['issue_code'], unique=False)
    op.create_index(op.f('ix_execution_review_issues_order_id'), 'execution_review_issues', ['order_id'], unique=False)
    op.create_index(op.f('ix_execution_review_issues_organization_id'), 'execution_review_issues', ['organization_id'], unique=False)
    op.create_index(op.f('ix_execution_review_issues_project_id'), 'execution_review_issues', ['project_id'], unique=False)
    op.create_index(op.f('ix_execution_review_issues_severity'), 'execution_review_issues', ['severity'], unique=False)
    op.create_index(op.f('ix_execution_review_issues_status'), 'execution_review_issues', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_review_issues_status'), table_name='execution_review_issues')
    op.drop_index(op.f('ix_execution_review_issues_severity'), table_name='execution_review_issues')
    op.drop_index(op.f('ix_execution_review_issues_project_id'), table_name='execution_review_issues')
    op.drop_index(op.f('ix_execution_review_issues_organization_id'), table_name='execution_review_issues')
    op.drop_index(op.f('ix_execution_review_issues_order_id'), table_name='execution_review_issues')
    op.drop_index(op.f('ix_execution_review_issues_issue_code'), table_name='execution_review_issues')
    op.drop_index(op.f('ix_execution_review_issues_dataset_version_id'), table_name='execution_review_issues')
    op.drop_index(op.f('ix_execution_review_issues_dataset_id'), table_name='execution_review_issues')
    op.drop_index(op.f('ix_execution_review_issues_assigned_to'), table_name='execution_review_issues')
    op.drop_table('execution_review_issues')
    # ### end Alembic commands ###
