"""Add execution review activity

Revision ID: 65f5be103c59
Revises: 3f6ac3ffd14d
Create Date: 2026-09-20 11:26:54.948812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65f5be103c59'
down_revision: Union[str, Sequence[str], None] = '3f6ac3ffd14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_review_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('review_issue_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('activity_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("activity_type IN ('COMMENT', 'STATUS_CHANGED', 'ASSIGNED')", name='ck_execution_review_activity_type'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_issue_id'], ['execution_review_issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_review_activities_activity_type'), 'execution_review_activities', ['activity_type'], unique=False)
    op.create_index(op.f('ix_execution_review_activities_author_id'), 'execution_review_activities', ['author_id'], unique=False)
    op.create_index(op.f('ix_execution_review_activities_created_at'), 'execution_review_activities', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_review_activities_organization_id'), 'execution_review_activities', ['organization_id'], unique=False)
    op.create_index(op.f('ix_execution_review_activities_project_id'), 'execution_review_activities', ['project_id'], unique=False)
    op.create_index(op.f('ix_execution_review_activities_review_issue_id'), 'execution_review_activities', ['review_issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_review_activities_review_issue_id'), table_name='execution_review_activities')
    op.drop_index(op.f('ix_execution_review_activities_project_id'), table_name='execution_review_activities')
    op.drop_index(op.f('ix_execution_review_activities_organization_id'), table_name='execution_review_activities')
    op.drop_index(op.f('ix_execution_review_activities_created_at'), table_name='execution_review_activities')
    op.drop_index(op.f('ix_execution_review_activities_author_id'), table_name='execution_review_activities')
    op.drop_index(op.f('ix_execution_review_activities_activity_type'), table_name='execution_review_activities')
    op.drop_table('execution_review_activities')
    # ### end Alembic commands ###
