"""add execution order and fill tables

Revision ID: c9a5a3a89c58
Revises: 373d4379d726
Create Date: 2026-09-08 06:04:09.777972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a5a3a89c58'
down_revision: Union[str, Sequence[str], None] = '373d4379d726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('external_order_id', sa.String(length=150), nullable=True),
    sa.Column('client_order_id', sa.String(length=150), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('order_type', sa.String(length=30), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('algorithm', sa.String(length=100), nullable=True),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('limit_price IS NULL OR limit_price >= 0', name='ck_execution_order_limit_price_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_execution_order_quantity_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_orders_client_order_id'), 'execution_orders', ['client_order_id'], unique=False)
    op.create_index(op.f('ix_execution_orders_created_by'), 'execution_orders', ['created_by'], unique=False)
    op.create_index(op.f('ix_execution_orders_external_order_id'), 'execution_orders', ['external_order_id'], unique=False)
    op.create_index(op.f('ix_execution_orders_organization_id'), 'execution_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_execution_orders_project_id'), 'execution_orders', ['project_id'], unique=False)
    op.create_index(op.f('ix_execution_orders_side'), 'execution_orders', ['side'], unique=False)
    op.create_index(op.f('ix_execution_orders_status'), 'execution_orders', ['status'], unique=False)
    op.create_index(op.f('ix_execution_orders_submitted_at'), 'execution_orders', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_execution_orders_symbol'), 'execution_orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_execution_orders_venue'), 'execution_orders', ['venue'], unique=False)
    op.create_table('execution_fills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_order_id', sa.UUID(), nullable=False),
    sa.Column('external_fill_id', sa.String(length=150), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('venue', sa.String(length=100), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('commission', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('fees', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('commission IS NULL OR commission >= 0', name='ck_execution_fill_commission_non_negative'),
    sa.CheckConstraint('fees IS NULL OR fees >= 0', name='ck_execution_fill_fees_non_negative'),
    sa.CheckConstraint('price >= 0', name='ck_execution_fill_price_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_execution_fill_quantity_positive'),
    sa.ForeignKeyConstraint(['execution_order_id'], ['execution_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_fills_executed_at'), 'execution_fills', ['executed_at'], unique=False)
    op.create_index(op.f('ix_execution_fills_execution_order_id'), 'execution_fills', ['execution_order_id'], unique=False)
    op.create_index(op.f('ix_execution_fills_external_fill_id'), 'execution_fills', ['external_fill_id'], unique=False)
    op.create_index(op.f('ix_execution_fills_venue'), 'execution_fills', ['venue'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_fills_venue'), table_name='execution_fills')
    op.drop_index(op.f('ix_execution_fills_external_fill_id'), table_name='execution_fills')
    op.drop_index(op.f('ix_execution_fills_execution_order_id'), table_name='execution_fills')
    op.drop_index(op.f('ix_execution_fills_executed_at'), table_name='execution_fills')
    op.drop_table('execution_fills')
    op.drop_index(op.f('ix_execution_orders_venue'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_symbol'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_submitted_at'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_status'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_side'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_project_id'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_organization_id'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_external_order_id'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_created_by'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_client_order_id'), table_name='execution_orders')
    op.drop_table('execution_orders')
    # ### end Alembic commands ###
