"""create research workspaces

Revision ID: ead65f8c2b53
Revises: a18df4d998c0
Create Date: 2026-10-07 17:16:04.932189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ead65f8c2b53'
down_revision: Union[str, Sequence[str], None] = 'a18df4d998c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('dataset_version_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete="RESTRICT"),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_workspaces_created_by'), 'research_workspaces', ['created_by'], unique=False)
    op.create_index(op.f('ix_research_workspaces_dataset_id'), 'research_workspaces', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_research_workspaces_dataset_version_id'), 'research_workspaces', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_research_workspaces_organization_id'), 'research_workspaces', ['organization_id'], unique=False)
    op.create_index(op.f('ix_research_workspaces_project_id'), 'research_workspaces', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_workspaces_status'), 'research_workspaces', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_workspaces_status'), table_name='research_workspaces')
    op.drop_index(op.f('ix_research_workspaces_project_id'), table_name='research_workspaces')
    op.drop_index(op.f('ix_research_workspaces_organization_id'), table_name='research_workspaces')
    op.drop_index(op.f('ix_research_workspaces_dataset_version_id'), table_name='research_workspaces')
    op.drop_index(op.f('ix_research_workspaces_dataset_id'), table_name='research_workspaces')
    op.drop_index(op.f('ix_research_workspaces_created_by'), table_name='research_workspaces')
    op.drop_table('research_workspaces')
    # ### end Alembic commands ###
