from __future__ import annotations

import json
from typing import Any

from app.services.research.research_copilot_service import ResearchLLMProvider


class AIResearchInsightsService:
    """
    Generate an AI-written research summary from Quantara's deterministic
    research insights.

    The LLM does not calculate financial metrics. It only synthesizes structured insights
    and supporting evidence produced by Quantara.
    """

    def __init__(
        self,
        *,
        provider: ResearchLLMProvider,
    ):

        self.provider = provider

    
    def generate_summary(
        self,
        *,
        insights: list[dict[str, Any]],
        context: dict[str, Any] | None = None,
    ) -> str:
        
        if not isinstance(insights, list):
            raise ValueError(
                "insights must be a list."
            )

        if not insights:
            raise ValueError(
                "At least one research insight is required."
            )

        if context is None:
            context = {}

        if not isinstance(context, dict):
            raise ValueError(
                "context must be a dictionary."
            )

        system_prompt = self._build_system_prompt()

        user_prompt=  self._build_user_prompt(
            insights=insights,
            context=context,
        )

        summary = self.provider.generate(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
        )

        if not summary or not summary.strip():
            raise RuntimeError(
                "AI provider returned an empty research summary."
            )

        return summary.strip()


    @staticmethod
    def _build_system_prompt() -> str:
        return """
You are Quantara's AI Research Insights Analyst.

Your task is to synthesize deterministic research insights generated by
Quantara's financial analysis engine into a concise professional research
summary.

The supplied insights and deterministic context are the source of truth.

Rules:

1. Do not invent financial metrics, prices, dates, events, or observations.
2. Do not recalculate metrics.
3. Do not introduce facts that are not present in the supplied context or insights.
4. Preserve the exact direction and meaning of the supplied insights.
5. Distinguish observed evidence from interpretation.
6. Do not claim causality unless it is explicitly established by the supplied evidence.
7. Mention important data-quality limitations when they are present.
8. Do not provide personalized investment advice or trading instructions.
9. Do not fabricate missing benchmark, market, or historical information.
10. If the evidence is limited, explicitly state that the conclusion is limited by the available evidence.
11. Prioritize material findings over minor observations.
12. Keep the summary concise and suitable for an institutional research workspace.
13. Treat Quantara's deterministic data-quality assessment as authoritative.
14. A quality check marked "not_applicable" is not a failed quality check.
15. Do not describe a dataset as low-quality when Quantara reports a high
    quality score or research_ready=true.
16. Distinguish dataset-quality limitations from statistical limitations.
17. A small sample or short observation window may limit the strength of
    conclusions, but this does not by itself mean the underlying dataset
    is low quality.
18. Do not reinterpret or contradict deterministic evidence.

Structure the response as:

Overall Assessment
Key Findings
Risk Considerations
Data Limitations

Only include sections that are supported by the supplied evidence.
""".strip()

    @staticmethod
    def _build_user_prompt(
        *,
        insights: list[dict[str, Any]],
        context: dict[str, Any],
    ) -> str:
        serialized_insights = json.dumps(
            insights,
            default=str,
            indent=2,
        )

        serialized_context = json.dumps(
            context,
            default=str,
            indent=2,
        )

        return f"""
Quantara deterministic research insights:

{serialized_insights}

Quantara research context:

{serialized_context}

Write a concise institutional-quality research summary using only the
supplied deterministic insights and context.

Do not introduce unsupported information.
Do not recalculate any metric.
Do not provide investment advice.
""".strip()