from __future__ import annotations

import json
from abc import ABC, abstractmethod
from typing import Any


class ResearchLLMProvider(ABC):
    """
    Provider interface for Quantara's AI Research Copilot.

    Concrete implementations can use Ollama, OpenAI, or another
    compatible provider without changing the Copilot orchestration layer.
    """

    name: str = "unknown"

    @abstractmethod
    def generate(
        self,
        *,
        system_prompt: str,
        user_prompt: str,
    ) -> str:
        """
        Generate a research answer from the supplied prompts.
        """
        raise NotImplementedError


class ResearchCopilotService:
    """
    Orchestrate Quantara research-context generation and LLM reasoning.

    The service deliberately keeps deterministic financial calculations
    outside the LLM. The LLM receives structured evidence generated by
    Quantara's analysis services.
    """

    def __init__(
        self,
        *,
        context_service: Any,
        provider: ResearchLLMProvider,
    ):
        self.context_service = context_service
        self.provider = provider

    def answer(
        self,
        *,
        dataframe: Any,
        question: str,
        file_path: str | None = None,
        symbols: list[str] | None = None,
        periods_per_year: int = 252,
    ) -> dict[str, Any]:
        if not question or not question.strip():
            raise ValueError("Research question cannot be empty.")

        context_result = self.context_service.build(
            dataframe=dataframe,
            question=question,
            file_path=file_path,
            symbols=symbols,
            periods_per_year=periods_per_year,
        )

        system_prompt = self._build_system_prompt()

        user_prompt = self._build_user_prompt(
            question=question,
            context=context_result["context"],
            evidence=context_result["evidence"],
        )

        answer = self.provider.generate(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
        )

        return {
            "answer": answer,
            "provider": self.provider.name,
            "context": context_result["context"],
            "evidence": context_result["evidence"],
        }

    @staticmethod
    def _build_system_prompt() -> str:
        return """
            You are Quantara's AI Research Copilot.

            You assist quantitative researchers and institutional investment teams
            with research questions about market data.

            Your job is to reason ONLY from the Quantara evidence and context supplied
            in the user prompt.

            Rules:

            1. Do not invent financial metrics, observations, prices, dates, or events.
            2. Do not claim that one variable caused another unless the supplied
            evidence establishes causality.
            3. Clearly distinguish observed results from interpretation.
            4. Use the exact metrics supplied by Quantara whenever possible.
            5. If the evidence is insufficient to answer the question, say so.
            6. Do not fabricate missing benchmark data.
            7. Do not provide investment advice or personalized trading instructions.
            8. When discussing performance, mention the relevant return, volatility,
            drawdown, beta, correlation, or other supplied evidence where applicable.
            9. Keep the answer concise but analytically useful.
            10. Explicitly mention important data-quality limitations when they affect
                the reliability of the conclusion.

            Structure the response as:

            Conclusion
            Evidence
            Interpretation
            Limitations

            The response should read like a professional quantitative research note,
            not like a generic chatbot response.
            """.strip()

    @staticmethod
    def _build_user_prompt(
        *,
        question: str,
        context: dict[str, Any],
        evidence: list[dict[str, Any]],
    ) -> str:
        serialized_context = json.dumps(
            context,
            default=str,
            indent=2,
        )

        serialized_evidence = json.dumps(
            evidence,
            default=str,
            indent=2,
        )

        return f"""
            Research question:

            {question.strip()}

            Quantara research context:

            {serialized_context}

            Quantara deterministic evidence:

            {serialized_evidence}

            Answer the research question using only the supplied Quantara context
            and deterministic evidence.

            Do not introduce unsupported facts.
            """.strip()